kind: pipeline
type: docker
name: build_container

steps:
  - name: drone_yml_lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -d relaxed .drone.yml

  - name: dockerfile_lint
    image: hadolint/hadolint:v1.18.0
    commands:
      - hadolint ketchup/Dockerfile

  - name: docker_build
    image: plugins/docker:18.09.2
    settings:
      dockerfile: ketchup/Dockerfile
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      repo: hsmtkk/infra-ci-book
      tags:
        - ketchup

---
kind: pipeline
type: docker
name: test_container

steps:
  - name: test_container
    image: curlimages/curl:7.71.1
    commands:
      - curl -L http://ketchup/admin

services:
  - name: ketchup
    image: hsmtkk/infra-ci-book:ketchup

depends_on:
  - build_container

